### PR TITLE
WWW-2168 Lets Eat RSS Template - add styling for horizontal rule

### PR DESCRIPTION
**Pull request by vance224**
https://jira.phillynews.com/browse/WWW-2168

### CODE REVIEW

**Review by mikhaia — COMMENTED** [review]
Hi @vance224 
https://i3.createsend1.com/ei/d/D5/42E/701/011506/csfinal/red-line1-990000079e04513c.gif
This image is not temporary?

**Comment by vance224** [comment]
> Hi @vance224
> https://i3.createsend1.com/ei/d/D5/42E/701/011506/csfinal/red-line1-990000079e04513c.gif
> This image is not temporary?

I think. It's old behavior and avoids to incur another bug. 
And then We cannot move it to Anglerfish because of it less than 1kb
So could we move forward with that?

**Comment by mikhaia** [comment]
red-line
Just attach the image here for backup and make sure that is will be safe.

**Review by mikhaia — APPROVED** [review]
Good to go!

**Pull request merged**
